service_name       = "<+pipeline.variables.service_name>"
service_identifier = "<+pipeline.variables.service_identifier>"
service_type       = "<+pipeline.variables.service_type>"
org_id             = "<+org.org.identifier>"
proj_id            = "<+project.identifier>"
